### ISSUE TITLE
Difference in REN-P3 energies after update.

### ISSUE THREAD

**Issue by DavidArchila** [efposadac/openLOWDIN#67]

**Comment by DavidArchila** [comment]
Same input file, two different running dates. Outfiles of both attached here. The problem seems to be in HF SCF initial cycle. 
[F2_2_old.txt](https://github.com/efposadac/openLOWDIN/files/14337634/F2_2_old.txt)
[F2_2_new.txt](https://github.com/efposadac/openLOWDIN/files/14337636/F2_2_new.txt)

**Comment by DavidArchila** [comment]
Thanks :D

**Comment by jacharrym** [comment]
For F basis, the coefficients of the last 2 P orbitals are different

new
             1         P                0.66970211          0.44202901
             1         P                0.21651300          0.24319876
old
             1         P                0.66970211          1.00000000
             1         P                0.21651300          1.00000000

Could you please try the new version with the old basis?

**Comment by DavidArchila** [comment]
The current output was using basis sets form BSE, as we noticed the change in those coefficients. It has small changes in the REN-P3 energy, but apparently not that much for the HF SCF.

**Comment by fsmoncadaa** [comment]
Hi David. I tried this calculation with the latest master version and got the results of the F2_2_old.txt file (TOTAL ENERGY =         -199.276401838187). Looking at the output files, I observe that in your new calculation the SCF converged to an antibonding sigma positronic orbital

 Occupied Eigenvectors for: E+SINGLET
 --------------------------- 
    1    E+S     S      -0.519503
    2    E+S     S      -0.823894
    3    E+S     S      -0.202933
    4    E+S     S       0.069414
    5    E+S     S       0.071804
    6    E+S     S       0.008813
    ...
   57    E+S     S       0.519503
   58    E+S     S       0.823894
   59    E+S     S       0.202933
   60    E+S     S      -0.069414
   61    E+S     S      -0.071804
   62    E+S     S      -0.008813
   
  Whereas before it was a bonding sigma positronic orbital

  Eigenvectors for: E+SINGLET
 -----------------
    1     E+S    S       0.115458 
    2     E+S    S       0.424261    
    3     E+S    S       0.190140 
    4     E+S    S      -0.058275 
    5     E+S    S      -0.074828 
    6     E+S    S      -0.009682   
    ...
   57     E+S    S       0.115458 
   58     E+S    S       0.424261 
   59     E+S    S       0.190140  
   60     E+S    S      -0.058275  
   61     E+S    S      -0.074828    
   62     E+S    S      -0.009682    

This is a consequence of the hcore guess, which is specially bad for positronic orbitals, because the positron only see potential of the nucleus in this guess. My recommendation is to always try to provide guess orbitals (readCoefficients=.T.). You can generate the guess orbitals running a calculation with positron basis, but without positron (addParticles=-2).

On a side note. The propagator theory correction of third order only works for singly occupied orbitals. That's why you have to use UHF, and also you shouldn't use E+S. So, to get numerically correct results with this method, please use positronic open shell:
E+A    PSX-TZ                    0.0                       0.0                       4.649045778944169e-05     
E+A    PSX-TZ                    2.947531666387118         -3.5728677438046077e-06   2.3916200483981832e-05    addParticles=-1 E+B    PSX-TZ                    0.0                       0.0                       4.649045778944169e-05     
E+B    PSX-TZ                    2.947531666387118         -3.5728677438046077e-06   2.3916200483981832e-05    addParticles=-1

**Comment by DavidArchila** [comment]
¡Thank you! I'll try it out.
