### ISSUE TITLE
Alternative for auxilary indexes or <ab||ij> elements

### ISSUE THREAD

**Issue by rafa-pr** [efposadac/openLOWDIN#92]
Hello all, 

Checking the way transformed integrals are accessed, seems always is managed with a auxiliary index. The thing is that i need to calculate <ab||ij> values, based on what ive seen, chemist notation is used on LOWDIN so the operation would be (ai|bj)-(aj|bi) with a,b virtuals and i,j occupied. I'll add a slice of the code:

            do a =  1+numberOcc,numberOfContractions
                do b = 1+numberOcc,numberOfContractions
                    do i = 1,numberOcc
                        do j = 1,numberOcc

                            auxIndex2 = IndexMap_tensorR4ToVectorB(int(a,8),int(i,8),int(b,8),int(j,8), &
                                                        int(numberOfContractions,8) )

                            auxIndex1 = IndexMap_tensorR4ToVectorB(int(a,8),int(j,8),int(b,8),int(i,8), &
                                                        int(numberOfContractions,8) )

                            auxVal_C = auxMatrix(k)%values(auxIndex2,1) - auxMatrix(k)%values(auxIndex1,1)

With auxVal_C being the final value of <ab||ij>. However, due to the auxiliary index they both values end up being the same and the values are always zero on all cases. 

Is there a way to access these elements without the use of auxIndexes or manage the values of the integrals so operation is non zero?  

I'll be looking into it if more information is needed. Thanks in advance. 

Best.

**Comment by jacharrym** [comment]
Helllo @rafa-pr 

I checked your slice of the code, and everything seems fine, the index_map function is working as intended

Question,  how many particles are you testing? 

Because for the case of one particle per quantum species, the coulomb and exchange will cancel out, exactly as in the case that you are observing. But if you try for more than one particle per species, some values of auxVal_C are not zero.

Now, regarding your question. There is no other way to access those integrals. Avoiding that indexmap function will require storing all the integrals (pq | rs)  elements in a four-dimensional array, N**4. However, due to the symmetry, there are 8 eight possible index permutations that correspond to the same integrals. In the end, all unique integrals are just (M + 1)M/2 , where M is (N+1)N/2. Therefore, to save resources, Lowdin stores only the upper triangular matrix (in analogy with a 2-dimensional array) in a vector format. But the cost of doing that is that we lost information regarding the index pqrs, only the integral value is stored. That s why we need the index map function to map any index p,q,r,s to the integral index in the reduced vector format.

Best,

**Comment by rafa-pr** [comment]
Hello @jacharrym,

At the moment is just one species but multiple particles; running a test on C STO-3G: 5 total contractions with 3 occupied and 2 virtual MO orbitals, so it would be a total of 625 integrals, in the end only 442 nonzero integrals are transformed and the elements needed for evaluation (auxVal_C) would be 36 (over the loop). As you comment employing the indexes, these are only different when all a,b,i and j are different causing that on iterations where the value should be non zero e.g <44||12> =  (41|42) - (42|41), the same index is achieved on each auxiliary one and the element goes to zero. Sending the printing of the elements for the aforementioned example:

           a           b           i           j         <ab||ij>                 auxIndex2       auxIndex1
           4           4           1           1 /   0.0000000000000000      /          43 /          43
           4           4           1           2 /   0.0000000000000000      /          47 /          47
           4           4           1           3 /   0.0000000000000000      /          50 /          50
           4           4           2           1 /   0.0000000000000000      /          47 /          47
           4           4           2           2 /   0.0000000000000000      /          85 /          85
           4           4           2           3 /   0.0000000000000000      /          88 /          88
           4           4           3           1 /   0.0000000000000000      /          50 /          50
           4           4           3           2 /   0.0000000000000000      /          88 /          88
           4           4           3           3 /   0.0000000000000000      /         106 /         106
           4           5           1           1 /   0.0000000000000000      /          44 /          44
           4           5           1           2 /   0.0000000000000000      /          48 /          58
           4           5           1           3 /   0.0000000000000000      /          51 /          61
           4           5           2           1 /   0.0000000000000000      /          58 /          48
           4           5           2           2 /   0.0000000000000000      /          86 /          86
           4           5           2           3 /   0.0000000000000000      /          89 /          95
           4           5           3           1 /   0.0000000000000000      /          61 /          51
           4           5           3           2 /   0.0000000000000000      /          95 /          89
           4           5           3           3 /   0.0000000000000000      /         107 /         107
           5           4           1           1 /   0.0000000000000000      /          44 /          44
           5           4           1           2 /   0.0000000000000000      /          58 /          48
           5           4           1           3 /   0.0000000000000000      /          61 /          51
           5           4           2           1 /   0.0000000000000000      /          48 /          58
           5           4           2           2 /   0.0000000000000000      /          86 /          86
           5           4           2           3 /   0.0000000000000000      /          95 /          89
           5           4           3           1 /   0.0000000000000000      /          51 /          61
           5           4           3           2 /   0.0000000000000000      /          89 /          95
           5           4           3           3 /   0.0000000000000000      /         107 /         107
           5           5           1           1 /   0.0000000000000000      /          55 /          55
           5           5           1           2 /   0.0000000000000000      /          59 /          59
           5           5           1           3 /   0.0000000000000000      /          62 /          62
           5           5           2           1 /   0.0000000000000000      /          59 /          59
           5           5           2           2 /   0.0000000000000000      /          93 /          93
           5           5           2           3 /   0.0000000000000000      /          96 /          96
           5           5           3           1 /   0.0000000000000000      /          62 /          62
           5           5           3           2 /   0.0000000000000000      /          96 /          96
           5           5           3           3 /   0.0000000000000000      /         111 /         111
 ===============================================

You mentioned the alternative of storing the integrals on a 4D arrays with each dimension with the number of contractions, but before looking into it (also cause I dont know how could they could be stored as such), is there a way to manipulate the indexes to avoid the issue at hand?

Best,

**Comment by jacharrym** [comment]
I did the same test and I got the same results for C STO-3G

```
a	b	I	j	index1	index2	( a i | b j )	( a j | b i )	(a i | b j) – ( a j | b i )
4	4	1	1	43	43	0.0215	0.0215	0.0000
4	4	1	2	47	47	0.0291	0.0291	0.0000
4	4	1	3	50	50	0.0000	0.0000	0.0000
4	4	2	1	47	47	0.0291	0.0291	0.0000
4	4	2	2	85	85	0.1308	0.1308	0.0000
4	4	2	3	88	88	0.0000	0.0000	0.0000
4	4	3	1	50	50	0.0000	0.0000	0.0000
4	4	3	2	88	88	0.0000	0.0000	0.0000
4	4	3	3	106	106	0.0363	0.0363	0.0000
4	5	1	1	44	44	0.0000	0.0000	0.0000
4	5	1	2	58	48	0.0000	0.0000	0.0000
4	5	1	3	61	51	0.0000	0.0000	0.0000
4	5	2	1	48	58	0.0000	0.0000	0.0000
4	5	2	2	86	86	0.0000	0.0000	0.0000
4	5	2	3	95	89	0.0000	0.0000	0.0000
4	5	3	1	51	61	0.0000	0.0000	0.0000
4	5	3	2	89	95	0.0000	0.0000	0.0000
4	5	3	3	107	107	0.0000	0.0000	0.0000
5	4	1	1	44	44	0.0000	0.0000	0.0000
5	4	1	2	48	58	0.0000	0.0000	0.0000
5	4	1	3	51	61	0.0000	0.0000	0.0000
5	4	2	1	58	48	0.0000	0.0000	0.0000
5	4	2	2	86	86	0.0000	0.0000	0.0000
5	4	2	3	89	95	0.0000	0.0000	0.0000
5	4	3	1	61	51	0.0000	0.0000	0.0000
5	4	3	2	95	89	0.0000	0.0000	0.0000
5	4	3	3	107	107	0.0000	0.0000	0.0000
5	5	1	1	55	55	0.0215	0.0215	0.0000
5	5	1	2	59	59	0.0291	0.0291	0.0000
5	5	1	3	62	62	0.0000	0.0000	0.0000
5	5	2	1	59	59	0.0291	0.0291	0.0000
5	5	2	2	93	93	0.1308	0.1308	0.0000
5	5	2	3	96	96	0.0000	0.0000	0.0000
5	5	3	1	62	62	0.0000	0.0000	0.0000
5	5	3	2	96	96	0.0000	0.0000	0.0000
5	5	3	3	111	111	0.0363	0.0363	0.0000
4	4	1	1	43	43	0.0215	0.0215	0.0000
4	4	1	2	47	47	0.0291	0.0291	0.0000
4	4	1	3	50	50	0.0000	0.0000	0.0000
4	4	2	1	47	47	0.0291	0.0291	0.0000
4	4	2	2	85	85	0.1308	0.1308	0.0000
4	4	2	3	88	88	0.0000	0.0000	0.0000
4	4	3	1	50	50	0.0000	0.0000	0.0000
4	4	3	2	88	88	0.0000	0.0000	0.0000
4	4	3	3	106	106	0.0363	0.0363	0.0000
4	5	1	1	44	44	0.0000	0.0000	0.0000
4	5	1	2	58	48	0.0000	0.0000	0.0000
4	5	1	3	61	51	0.0000	0.0000	0.0000
4	5	2	1	48	58	0.0000	0.0000	0.0000
4	5	2	2	86	86	0.0000	0.0000	0.0000
4	5	2	3	95	89	0.0000	0.0000	0.0000
4	5	3	1	51	61	0.0000	0.0000	0.0000
4	5	3	2	89	95	0.0000	0.0000	0.0000
4	5	3	3	107	107	0.0000	0.0000	0.0000
5	4	1	1	44	44	0.0000	0.0000	0.0000
5	4	1	2	48	58	0.0000	0.0000	0.0000
5	4	1	3	51	61	0.0000	0.0000	0.0000
5	4	2	1	58	48	0.0000	0.0000	0.0000
5	4	2	2	86	86	0.0000	0.0000	0.0000
5	4	2	3	89	95	0.0000	0.0000	0.0000
5	4	3	1	61	51	0.0000	0.0000	0.0000
5	4	3	2	95	89	0.0000	0.0000	0.0000
5	4	3	3	107	107	0.0000	0.0000	0.0000
5	5	1	1	55	55	0.0215	0.0215	0.0000
5	5	1	2	59	59	0.0291	0.0291	0.0000
5	5	1	3	62	62	0.0000	0.0000	0.0000
5	5	2	1	59	59	0.0291	0.0291	0.0000
5	5	2	2	93	93	0.1308	0.1308	0.0000
5	5	2	3	96	96	0.0000	0.0000	0.0000
5	5	3	1	62	62	0.0000	0.0000	0.0000
5	5	3	2	96	96	0.0000	0.0000	0.0000
5	5	3	3	111	111	0.0363	0.0363	0.0000
```

Here, notice there are multiple cases:
1. index1 and index2 are equal, and the integrals aibj and ajbi are nonzero, therefore, aux_valC is zero
2. index1 and index2 are equal, and the integrals aibj and ajbi are zero, therefore, aux_valC is zero
3. index1 and index2 are different, but integral aibj and ajbi are zero, therefore auxValC is zero
what is missing there is the case
4. index1 and index2 are different, but integral aibj and ajbi are nonzero, therefore auxValC should be nonzero

However, if you increase the basis to 3-21G, you will obtain the 4th case

```
a	b	I	j	index1	index2	( a i | b j )	( a j | b i )	(a i | b j) – ( a j | b i )
4	4	1	1	133	133	0.0124	0.0124	0.0000
4	4	1	2	141	141	0.0179	0.0179	0.0000
4	4	1	3	148	148	0.0000	0.0000	0.0000
4	4	2	1	141	141	0.0179	0.0179	0.0000
4	4	2	2	441	441	0.1066	0.1066	0.0000
4	4	2	3	448	448	0.0000	0.0000	0.0000
4	4	3	1	148	148	0.0000	0.0000	0.0000
4	4	3	2	448	448	0.0000	0.0000	0.0000
4	4	3	3	658	658	0.0275	0.0275	0.0000
4	5	1	1	134	134	0.0000	0.0000	0.0000
4	5	1	2	182	142	0.0000	0.0000	0.0000
4	5	1	3	189	149	0.0000	0.0000	0.0000
4	5	2	1	142	182	0.0000	0.0000	0.0000
4	5	2	2	442	442	0.0000	0.0000	0.0000
4	5	2	3	481	449	0.0000	0.0000	0.0000
4	5	3	1	149	189	0.0000	0.0000	0.0000
4	5	3	2	449	481	0.0000	0.0000	0.0000
4	5	3	3	659	659	0.0000	0.0000	0.0000
4	6	1	1	135	135	0.0000	0.0000	0.0000
4	6	1	2	222	143	0.0000	0.0000	0.0000
4	6	1	3	229	150	0.0000	0.0000	0.0000
4	6	2	1	143	222	0.0000	0.0000	0.0000
4	6	2	2	443	443	0.0000	0.0000	0.0000
4	6	2	3	513	450	0.0000	0.0000	0.0000
4	6	3	1	150	229	0.0000	0.0000	0.0000
4	6	3	2	450	513	0.0000	0.0000	0.0000
4	6	3	3	660	660	0.0000	0.0000	0.0000
4	7	1	1	136	136	-0.0241	-0.0241	0.0000
4	7	1	2	261	144	-0.0148	-0.0305	0.0158
4	7	1	3	268	151	0.0000	0.0000	0.0000
4	7	2	1	144	261	-0.0305	-0.0148	-0.0158
4	7	2	2	444	444	-0.0377	-0.0377	0.0000
4	7	2	3	544	451	0.0000	0.0000	0.0000
4	7	3	1	151	268	0.0000	0.0000	0.0000
4	7	3	2	451	544	0.0000	0.0000	0.0000
4	7	3	3	661	661	-0.0087	-0.0087	0.0000
4	8	1	1	137	137	-0.0003	-0.0003	0.0000
4	8	1	2	299	145	-0.0002	-0.0003	0.0002
4	8	1	3	306	152	0.0000	0.0000	0.0000
```

( I didn't copy the full data here)

The case of STO-3G is just simply an exception due to its symmetry where all of those transformed integrals are zero, the atomic integrals are probably nonzero, but the MO coefficients can be zero, probably due to the singles and p virtual orbitals.  If you go to larger basis set like 3-21G (3s2p) some of those virtual orbitals coefficients can be non zero, mixing two p probably. Furthermore, if you go beyond atoms to nonsymmetric molecules, more orbitals coefficients would be nonzero resulting on more nonzero integrals.

I don't know which equations you are following, but on many occasions, you can find an index restriction to avoid repeated indexes (case 1 and 2) which, even if the MO is nonzero, the repulsion energy (Coulomb - exchange) is zero by the symmetry of the indexes. 

The case that you mentioned, <44||12> = (41|42) - (42|41), is also symmetric, and it should be zero, that why the index1 and index2 are equal. You can check here an example of all the two-particle integral symmetry
https://en.wikipedia.org/wiki/Yoshimine_sort 
therefore the symmetry ( pq | rs ) = ( rs | pq ) also exists. 

So, I don't see an issue, everything is working as expected. 

If you want to know, storing the integrals in a 4D array is simple. Just at the moment of integral calculation or transformation create an array tensor(:,:,:,:) and save the integrals at tensor(p,q,r,s)

I hope this answers your questions. 

Best regards.

**Comment by rafa-pr** [comment]
Hello @jacharrym,

Thanks for the response, i ran some other test on different systems and found the error im having with my implementation, which i now unrelated to the indexation. As you comment there is no issue.

Best,
